export interface City {
  name: string
  state: string
  tier: 1 | 2 | 3
  popular?: boolean
}

export const indianCities: City[] = [
  // Tier 1 Cities (Metro Cities)
  { name: 'Mumbai', state: 'Maharashtra', tier: 1, popular: true },
  { name: 'Delhi', state: 'Delhi', tier: 1, popular: true },
  { name: 'Bangalore', state: 'Karnataka', tier: 1, popular: true },
  { name: 'Hyderabad', state: 'Telangana', tier: 1, popular: true },
  { name: 'Chennai', state: 'Tamil Nadu', tier: 1, popular: true },
  { name: 'Kolkata', state: 'West Bengal', tier: 1, popular: true },
  { name: 'Pune', state: 'Maharashtra', tier: 1, popular: true },
  { name: 'Ahmedabad', state: 'Gujarat', tier: 1, popular: true },

  // Tier 2 Cities
  { name: 'Surat', state: 'Gujarat', tier: 2 },
  { name: 'Jaipur', state: 'Rajasthan', tier: 2, popular: true },
  { name: 'Lucknow', state: 'Uttar Pradesh', tier: 2 },
  { name: 'Kanpur', state: 'Uttar Pradesh', tier: 2 },
  { name: 'Nagpur', state: 'Maharashtra', tier: 2 },
  { name: 'Indore', state: 'Madhya Pradesh', tier: 2 },
  { name: 'Thane', state: 'Maharashtra', tier: 2 },
  { name: 'Bhopal', state: 'Madhya Pradesh', tier: 2 },
  { name: 'Visakhapatnam', state: 'Andhra Pradesh', tier: 2 },
  { name: 'Vadodara', state: 'Gujarat', tier: 2 },
  { name: 'Ghaziabad', state: 'Uttar Pradesh', tier: 2 },
  { name: 'Ludhiana', state: 'Punjab', tier: 2 },
  { name: 'Agra', state: 'Uttar Pradesh', tier: 2 },
  { name: 'Nashik', state: 'Maharashtra', tier: 2 },
  { name: 'Faridabad', state: 'Haryana', tier: 2 },
  { name: 'Meerut', state: 'Uttar Pradesh', tier: 2 },
  { name: 'Rajkot', state: 'Gujarat', tier: 2 },
  { name: 'Varanasi', state: 'Uttar Pradesh', tier: 2 },
  { name: 'Srinagar', state: 'Jammu and Kashmir', tier: 2 },
  { name: 'Amritsar', state: 'Punjab', tier: 2 },
  { name: 'Allahabad', state: 'Uttar Pradesh', tier: 2 },
  { name: 'Ranchi', state: 'Jharkhand', tier: 2 },
  { name: 'Howrah', state: 'West Bengal', tier: 2 },
  { name: 'Coimbatore', state: 'Tamil Nadu', tier: 2 },
  { name: 'Jabalpur', state: 'Madhya Pradesh', tier: 2 },
  { name: 'Gwalior', state: 'Madhya Pradesh', tier: 2 },
  { name: 'Vijayawada', state: 'Andhra Pradesh', tier: 2 },
  { name: 'Jodhpur', state: 'Rajasthan', tier: 2 },
  { name: 'Madurai', state: 'Tamil Nadu', tier: 2 },
  { name: 'Raipur', state: 'Chhattisgarh', tier: 2 },
  { name: 'Kota', state: 'Rajasthan', tier: 2 },
  { name: 'Chandigarh', state: 'Chandigarh', tier: 2, popular: true },
  { name: 'Guwahati', state: 'Assam', tier: 2 },
  { name: 'Mysore', state: 'Karnataka', tier: 2 },
  { name: 'Bareilly', state: 'Uttar Pradesh', tier: 2 },
  { name: 'Aligarh', state: 'Uttar Pradesh', tier: 2 },
  { name: 'Moradabad', state: 'Uttar Pradesh', tier: 2 },
  { name: 'Jalandhar', state: 'Punjab', tier: 2 },
  { name: 'Bhubaneswar', state: 'Odisha', tier: 2 },
  { name: 'Salem', state: 'Tamil Nadu', tier: 2 },
  { name: 'Warangal', state: 'Telangana', tier: 2 },
  { name: 'Guntur', state: 'Andhra Pradesh', tier: 2 },
  { name: 'Bhiwandi', state: 'Maharashtra', tier: 2 },
  { name: 'Saharanpur', state: 'Uttar Pradesh', tier: 2 },
  { name: 'Gorakhpur', state: 'Uttar Pradesh', tier: 2 },
  { name: 'Bikaner', state: 'Rajasthan', tier: 2 },
  { name: 'Amravati', state: 'Maharashtra', tier: 2 },
  { name: 'Noida', state: 'Uttar Pradesh', tier: 2, popular: true },
  { name: 'Jamshedpur', state: 'Jharkhand', tier: 2 },
  { name: 'Bhilai', state: 'Chhattisgarh', tier: 2 },
  { name: 'Cuttack', state: 'Odisha', tier: 2 },
  { name: 'Firozabad', state: 'Uttar Pradesh', tier: 2 },
  { name: 'Kochi', state: 'Kerala', tier: 2, popular: true },
  { name: 'Nellore', state: 'Andhra Pradesh', tier: 2 },
  { name: 'Dehradun', state: 'Uttarakhand', tier: 2 },
  { name: 'Durgapur', state: 'West Bengal', tier: 2 },
  { name: 'Asansol', state: 'West Bengal', tier: 2 },
  { name: 'Nanded', state: 'Maharashtra', tier: 2 },
  { name: 'Kolhapur', state: 'Maharashtra', tier: 2 },
  { name: 'Ajmer', state: 'Rajasthan', tier: 2 },
  { name: 'Gulbarga', state: 'Karnataka', tier: 2 },
  { name: 'Jamnagar', state: 'Gujarat', tier: 2 },
  { name: 'Ujjain', state: 'Madhya Pradesh', tier: 2 },
  { name: 'Loni', state: 'Uttar Pradesh', tier: 2 },
  { name: 'Siliguri', state: 'West Bengal', tier: 2 },
  { name: 'Jhansi', state: 'Uttar Pradesh', tier: 2 },
  { name: 'Ulhasnagar', state: 'Maharashtra', tier: 2 },
  { name: 'Jammu', state: 'Jammu and Kashmir', tier: 2 },
  { name: 'Mangalore', state: 'Karnataka', tier: 2 },
  { name: 'Erode', state: 'Tamil Nadu', tier: 2 },
  { name: 'Belgaum', state: 'Karnataka', tier: 2 },
  { name: 'Ambattur', state: 'Tamil Nadu', tier: 2 },
  { name: 'Tirunelveli', state: 'Tamil Nadu', tier: 2 },
  { name: 'Malegaon', state: 'Maharashtra', tier: 2 },
  { name: 'Gaya', state: 'Bihar', tier: 2 },
  { name: 'Thiruvananthapuram', state: 'Kerala', tier: 2 },

  // Tier 3 Cities
  { name: 'Udaipur', state: 'Rajasthan', tier: 3 },
  { name: 'Tiruppur', state: 'Tamil Nadu', tier: 3 },
  { name: 'Maheshtala', state: 'West Bengal', tier: 3 },
  { name: 'Davanagere', state: 'Karnataka', tier: 3 },
  { name: 'Kozhikode', state: 'Kerala', tier: 3 },
  { name: 'Akola', state: 'Maharashtra', tier: 3 },
  { name: 'Kurnool', state: 'Andhra Pradesh', tier: 3 },
  { name: 'Rajpur Sonarpur', state: 'West Bengal', tier: 3 },
  { name: 'Bokaro', state: 'Jharkhand', tier: 3 },
  { name: 'South Dumdum', state: 'West Bengal', tier: 3 },
  { name: 'Bellary', state: 'Karnataka', tier: 3 },
  { name: 'Patiala', state: 'Punjab', tier: 3 },
  { name: 'Gopalpur', state: 'West Bengal', tier: 3 },
  { name: 'Agartala', state: 'Tripura', tier: 3 },
  { name: 'Bhagalpur', state: 'Bihar', tier: 3 },
  { name: 'Muzaffarnagar', state: 'Uttar Pradesh', tier: 3 },
  { name: 'Bhatpara', state: 'West Bengal', tier: 3 },
  { name: 'Panihati', state: 'West Bengal', tier: 3 },
  { name: 'Latur', state: 'Maharashtra', tier: 3 },
  { name: 'Dhule', state: 'Maharashtra', tier: 3 },
  { name: 'Rohtak', state: 'Haryana', tier: 3 },
  { name: 'Korba', state: 'Chhattisgarh', tier: 3 },
  { name: 'Bhilwara', state: 'Rajasthan', tier: 3 },
  { name: 'Brahmapur', state: 'Odisha', tier: 3 },
  { name: 'Muzaffarpur', state: 'Bihar', tier: 3 },
  { name: 'Ahmednagar', state: 'Maharashtra', tier: 3 },
  { name: 'Mathura', state: 'Uttar Pradesh', tier: 3 },
  { name: 'Kollam', state: 'Kerala', tier: 3 },
  { name: 'Avadi', state: 'Tamil Nadu', tier: 3 },
  { name: 'Kadapa', state: 'Andhra Pradesh', tier: 3 },
  { name: 'Kamarhati', state: 'West Bengal', tier: 3 },
  { name: 'Bilaspur', state: 'Chhattisgarh', tier: 3 },
  { name: 'Shahjahanpur', state: 'Uttar Pradesh', tier: 3 },
  { name: 'Satara', state: 'Maharashtra', tier: 3 },
  { name: 'Bijapur', state: 'Karnataka', tier: 3 },
  { name: 'Rampur', state: 'Uttar Pradesh', tier: 3 },
  { name: 'Shivamogga', state: 'Karnataka', tier: 3 },
  { name: 'Chandrapur', state: 'Maharashtra', tier: 3 },
  { name: 'Junagadh', state: 'Gujarat', tier: 3 },
  { name: 'Thrissur', state: 'Kerala', tier: 3 },
  { name: 'Alwar', state: 'Rajasthan', tier: 3 },
  { name: 'Bardhaman', state: 'West Bengal', tier: 3 },
  { name: 'Kulti', state: 'West Bengal', tier: 3 },
  { name: 'Kakinada', state: 'Andhra Pradesh', tier: 3 },
  { name: 'Nizamabad', state: 'Telangana', tier: 3 },
  { name: 'Parbhani', state: 'Maharashtra', tier: 3 },
  { name: 'Tumkur', state: 'Karnataka', tier: 3 },
  { name: 'Khammam', state: 'Telangana', tier: 3 },
  { name: 'Ozhukarai', state: 'Puducherry', tier: 3 },
  { name: 'Bihar Sharif', state: 'Bihar', tier: 3 },
  { name: 'Panipat', state: 'Haryana', tier: 3 },
  { name: 'Darbhanga', state: 'Bihar', tier: 3 },
  { name: 'Bally', state: 'West Bengal', tier: 3 },
  { name: 'Aizawl', state: 'Mizoram', tier: 3 },
  { name: 'Dewas', state: 'Madhya Pradesh', tier: 3 },
  { name: 'Ichalkaranji', state: 'Maharashtra', tier: 3 },
  { name: 'Karnal', state: 'Haryana', tier: 3 },
  { name: 'Bathinda', state: 'Punjab', tier: 3 },
  { name: 'Jalna', state: 'Maharashtra', tier: 3 },
  { name: 'Eluru', state: 'Andhra Pradesh', tier: 3 },
  { name: 'Kirari Suleman Nagar', state: 'Delhi', tier: 3 },
  { name: 'Barasat', state: 'West Bengal', tier: 3 },
  { name: 'Purnia', state: 'Bihar', tier: 3 },
  { name: 'Satna', state: 'Madhya Pradesh', tier: 3 },
  { name: 'Mau', state: 'Uttar Pradesh', tier: 3 },
  { name: 'Sonipat', state: 'Haryana', tier: 3 },
  { name: 'Farrukhabad', state: 'Uttar Pradesh', tier: 3 },
  { name: 'Sagar', state: 'Madhya Pradesh', tier: 3 },
  { name: 'Rourkela', state: 'Odisha', tier: 3 },
  { name: 'Durg', state: 'Chhattisgarh', tier: 3 },
  { name: 'Imphal', state: 'Manipur', tier: 3 },
  { name: 'Ratlam', state: 'Madhya Pradesh', tier: 3 },
  { name: 'Hapur', state: 'Uttar Pradesh', tier: 3 },
  { name: 'Arrah', state: 'Bihar', tier: 3 },
  { name: 'Karimnagar', state: 'Telangana', tier: 3 },
  { name: 'Anantapur', state: 'Andhra Pradesh', tier: 3 },
  { name: 'Etawah', state: 'Uttar Pradesh', tier: 3 },
  { name: 'Ambernath', state: 'Maharashtra', tier: 3 },
  { name: 'North Dumdum', state: 'West Bengal', tier: 3 },
  { name: 'Bharatpur', state: 'Rajasthan', tier: 3 },
  { name: 'Begusarai', state: 'Bihar', tier: 3 },
  { name: 'New Delhi', state: 'Delhi', tier: 3 },
  { name: 'Gandhidham', state: 'Gujarat', tier: 3 },
  { name: 'Baranagar', state: 'West Bengal', tier: 3 },
  { name: 'Tiruvottiyur', state: 'Tamil Nadu', tier: 3 },
  { name: 'Puducherry', state: 'Puducherry', tier: 3 },
  { name: 'Sikar', state: 'Rajasthan', tier: 3 },
  { name: 'Thoothukudi', state: 'Tamil Nadu', tier: 3 },
  { name: 'Raurkela Industrial Township', state: 'Odisha', tier: 3 },
  { name: 'Nagercoil', state: 'Tamil Nadu', tier: 3 },
  { name: 'Thanjavur', state: 'Tamil Nadu', tier: 3 },
  { name: 'Murwara', state: 'Madhya Pradesh', tier: 3 },
  { name: 'Naihati', state: 'West Bengal', tier: 3 },
  { name: 'Sambhal', state: 'Uttar Pradesh', tier: 3 },
  { name: 'Nadiad', state: 'Gujarat', tier: 3 },
  { name: 'Yamunanagar', state: 'Haryana', tier: 3 },
  { name: 'English Bazar', state: 'West Bengal', tier: 3 },
  { name: 'Raichur', state: 'Karnataka', tier: 3 },
  { name: 'Pali', state: 'Rajasthan', tier: 3 },
  { name: 'Morbi', state: 'Gujarat', tier: 3 },
  { name: 'Bhind', state: 'Madhya Pradesh', tier: 3 },
  { name: 'Bhalswa Jahangir Pur', state: 'Delhi', tier: 3 },
  { name: 'Madhyamgram', state: 'West Bengal', tier: 3 },
  { name: 'Bhiwani', state: 'Haryana', tier: 3 },
  { name: 'Navi Mumbai', state: 'Maharashtra', tier: 3 },
  { name: 'Baharampur', state: 'West Bengal', tier: 3 },
  { name: 'Ambala', state: 'Haryana', tier: 3 },
  { name: 'Morena', state: 'Madhya Pradesh', tier: 3 },
  { name: 'Raigarh', state: 'Chhattisgarh', tier: 3 },
  { name: 'Panchkula', state: 'Haryana', tier: 3 },
  { name: 'Burhanpur', state: 'Madhya Pradesh', tier: 3 },
  { name: 'Kharagpur', state: 'West Bengal', tier: 3 },
  { name: 'Dindigul', state: 'Tamil Nadu', tier: 3 },
  { name: 'Gandhinagar', state: 'Gujarat', tier: 3 },
  { name: 'Hospet', state: 'Karnataka', tier: 3 },
  { name: 'Nangloi Jat', state: 'Delhi', tier: 3 },
  { name: 'Malda', state: 'West Bengal', tier: 3 },
  { name: 'Ongole', state: 'Andhra Pradesh', tier: 3 },
  { name: 'Deoghar', state: 'Jharkhand', tier: 3 },
  { name: 'Chapra', state: 'Bihar', tier: 3 },
  { name: 'Haldia', state: 'West Bengal', tier: 3 },
  { name: 'Khandwa', state: 'Madhya Pradesh', tier: 3 },
  { name: 'Nandyal', state: 'Andhra Pradesh', tier: 3 },
  { name: 'Chittoor', state: 'Andhra Pradesh', tier: 3 },
  { name: 'Amroha', state: 'Uttar Pradesh', tier: 3 },
  { name: 'Anand', state: 'Gujarat', tier: 3 },
  { name: 'Haridwar', state: 'Uttarakhand', tier: 3 },
  { name: 'Virar', state: 'Maharashtra', tier: 3 },
  { name: 'Tenali', state: 'Andhra Pradesh', tier: 3 },
  { name: 'Khora', state: 'Uttar Pradesh', tier: 3 },
  { name: 'Guntakal', state: 'Andhra Pradesh', tier: 3 },
  { name: 'Udupi', state: 'Karnataka', tier: 3 },
  { name: 'Porbandar', state: 'Gujarat', tier: 3 },
  { name: 'Silchar', state: 'Assam', tier: 3 },
  { name: 'Rajahmundry', state: 'Andhra Pradesh', tier: 3 },
  { name: 'Bokaro Steel City', state: 'Jharkhand', tier: 3 },
  { name: 'Solan', state: 'Himachal Pradesh', tier: 3 },
  { name: 'Shimla', state: 'Himachal Pradesh', tier: 3 },
  { name: 'Gangtok', state: 'Sikkim', tier: 3 },
  { name: 'Shillong', state: 'Meghalaya', tier: 3 },
  { name: 'Itanagar', state: 'Arunachal Pradesh', tier: 3 },
  { name: 'Kohima', state: 'Nagaland', tier: 3 },
  { name: 'Dibrugarh', state: 'Assam', tier: 3 },
  { name: 'Jorhat', state: 'Assam', tier: 3 },
  { name: 'Tezpur', state: 'Assam', tier: 3 },
  { name: 'Kavaratti', state: 'Lakshadweep', tier: 3 },
  { name: 'Port Blair', state: 'Andaman and Nicobar Islands', tier: 3 },
  { name: 'Silvassa', state: 'Dadra and Nagar Haveli', tier: 3 },
  { name: 'Daman', state: 'Daman and Diu', tier: 3 },
]

// Helper function to get popular cities
export const getPopularCities = (): City[] => {
  return indianCities.filter(city => city.popular)
}

// Helper function to search cities
export const searchCities = (query: string): City[] => {
  if (!query.trim()) return []
  
  const lowerQuery = query.toLowerCase()
  return indianCities.filter(city =>
    city.name.toLowerCase().includes(lowerQuery) ||
    city.state.toLowerCase().includes(lowerQuery)
  )
}

// Helper function to get cities by state
export const getCitiesByState = (state: string): City[] => {
  return indianCities.filter(city => city.state === state)
}

// Helper function to get all states
export const getAllStates = (): string[] => {
  return Array.from(new Set(indianCities.map(city => city.state))).sort()
}
